kind: stack

depends:
- freedesktop-sdk.bst:gnome-shell
- freedesktop-sdk.bst:gnome-terminal
- freedesktop-sdk.bst:gnome-control-center
- freedesktop-sdk.bst:gnome-console
- freedesktop-sdk.bst:gnome-text-editor
- freedesktop-sdk.bst:gnome-calendar
- freedesktop-sdk.bst:gnome-clocks
- freedesktop-sdk.bst:gnome-weather
- freedesktop-sdk.bst:gnome-maps
- freedesktop-sdk.bst:gnome-contacts
- freedesktop-sdk.bst:gnome-music
- freedesktop-sdk.bst:gnome-photos
- freedesktop-sdk.bst:loupe
- freedesktop-sdk.bst:snapshot
- freedesktop-sdk.bst:gnome-calculator
- freedesktop-sdk.bst:gnome-characters
- freedesktop-sdk.bst:gnome-font-viewer
- freedesktop-sdk.bst:gnome-logs
- freedesktop-sdk.bst:gnome-system-monitor
- freedesktop-sdk.bst:gnome-disk-utility
- freedesktop-sdk.bst:baobab
- freedesktop-sdk.bst:file-roller
- freedesktop-sdk.bst:yelp
- freedesktop-sdk.bst:evince
- freedesktop-sdk.bst:totem