# /etc/bindmounts.d/terrace.conf
# Bind mounts for Terrace images

# User home directories
/var/home /home none bind,x-mount.mkdir 0 0

# Flatpak
/var/lib/flatpak /var/lib/flatpak none bind,x-mount.mkdir 0 0

# Podman
/var/lib/containers /var/lib/containers none bind,x-mount.mkdir 0 0

# Libvirt
/var/lib/libvirt /var/lib/libvirt none bind,x-mount.mkdir 0 0

# Distrobox
/var/lib/distrobox /var/lib/distrobox none bind,x-mount.mkdir 0 0