kind: stack

depends:
- freedesktop-sdk.bst:pipewire
- freedesktop-sdk.bst:pipewire-alsa
- freedesktop-sdk.bst:pipewire-jack
- freedesktop-sdk.bst:pipewire-pulse
- freedesktop-sdk.bst:wireplumber
- freedesktop-sdk.bst:libpipewire
- freedesktop-sdk.bst:gst-plugins-base
- freedesktop-sdk.bst:gst-plugins-good
- freedesktop-sdk.bst:gst-plugins-bad
- freedesktop-sdk.bst:gst-plugins-ugly
- freedesktop-sdk.bst:gst-libav
- freedesktop-sdk.bst:libcamera
- freedesktop-sdk.bst:libcanberra